trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'ansheno/bootcamp-demo2'

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: anshenoDockerHub
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile

