apiVersion: apps/v1
kind: Deployment
metadata:
  name: doggopy-demo-canary
  namespace: doggo
  labels:
    app: doggopy-demo-canary
spec:
  replicas: 6
  selector:
    matchLabels:
      app: doggopy-demo-canary
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: doggopy-demo-canary
    spec:
      containers:
      - name: doggopy-demo-canary
        image: ansheno/doggopy-demo:v2
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: "2"
        ports:
        - containerPort: 8000
        - containerPort: 8080
