apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-demo
  labels:
    app: bootcamp-demo
    company: smart-hotel
    service: python
    author: barsin
    backend: false
    frontend: true
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bootcamp-demo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: bootcamp-demo
        company: smart-hotel
        service: python
        author: barsin
        backend: false
        frontend: true
        exposed: true
    spec:
      containers:
      - name: bootcamp-demo
        image: shashankbarsin/bootcamp-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
