apiVersion: v1
kind: Service
metadata:
  name: doggopy-demo-canary
  namespace: doggo
  labels:
    app: doggopy-demo-canary
spec:
  selector:
    app: doggopy-demo-canary
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
